# Generated by Django 3.2.9 on 2021-11-12 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.TextField()),
                ('email', models.TextField()),
                ('password', models.CharField(max_length=64)),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('bio', models.TextField()),
                ('birthday', models.DateTimeField()),
                ('avatar', models.TextField()),
                ('location', models.TextField()),
                ('fav_sport_1', models.TextField()),
                ('fav_sport_2', models.TextField()),
                ('fav_sport_3', models.TextField()),
                ('badge_1', models.TextField()),
                ('badge_2', models.TextField()),
                ('badge_3', models.TextField()),
                ('privacy', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='EventPost',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('title', models.TextField()),
                ('creation_date', models.DateTimeField()),
                ('location', models.TextField()),
                ('date', models.DateTimeField()),
                ('duration', models.TimeField()),
                ('sport', models.CharField(max_length=30)),
                ('age_group', models.IntegerField()),
                ('player_capacity', models.IntegerField()),
                ('spec_capacity', models.IntegerField()),
                ('players', models.IntegerField()),
                ('spectators', models.IntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventposts.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
