# Generated by Django 3.2.9 on 2021-12-10 20:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='creationDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='comment',
            name='creationDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
